### ISSUE TITLE
Cannot reshape a tensor

### ISSUE THREAD

**Issue by Heryakusuma** [patrickbryant1/MoLPC#10]
Hello!

When I tried to run the MoLPC, I ran into the following problem in the "Predict the subcomponents" section :

ValueError: Cannot reshape a tensor with 135324 elements to shape [358,381,1] (136398 elements) for '{{node reshape_msa}} = Reshape[T=DT_INT32, Tshape=DT_INT32](Const_6, reshape_msa/shape)' with input shapes: [358,378], [3] and with input tensors computed as partial shapes: input[1] = [358,381,1].

I attached the screenshot of when I got the error message
![Picture1](https://user-images.githubusercontent.com/121691584/210111939-daf888da-2e7c-4c87-bdfc-a4363cfd40f6.png)

Before I got this error, I ran the test case and it worked completely fine. I also ran a different protein sequence and I got the assembled model.

I ran the code in MoLPC google colab. It also gave me the same error whether either I am choosing a dimer or trimer interaction for assembly or changing the stoichiometry value.

How can I solve the problem?

Thank you very much.

PS: I do not know if this information is useful or not. My experiment data suggest that the protein (the one that gave me an error) might form a complex via a disulfide bond. I do not know the extent of the MoLPC prediction power for this kind of protein.

**Comment by patrickbryant1** [comment]
Hi,

This seems to be an error related to AlphaFold somehow. This is most likely related to some kind of inconsistency in the MSA. Please go through your MSAs and make sure they are a3m and do not contain any inconsistencies. You can compare with the test case here: https://github.com/patrickbryant1/MoLPC/blob/master/data/test/1A8R_1.a3m

**Comment by diogomaiasilva** [comment]
Hi @Heryakusuma and @patrickbryant1 ,

Have you found a solution for this issue?

I have the same error, and cannot find any inconsistency in format nor naming of the a3m file compared to the test case.

Thank you,
Diogo

**Comment by patrickbryant1** [comment]
Hi, I think this is related to the a3m parsing somehow resulting in a shape mismatch within AF. Is it possible something is wrong with the a3m vs fasta lengths? If you provide the msas we can look into what may be wrong. Please outline the issue and how you ran MolPC as clearly as possible.

**Comment by diogomaiasilva** [comment]
> 

I ran MoLPC in colab as per instructions, and everything worked well with the test case.

I manually checked the sequences and length of the FASTA and a3m, and they match.
My .a3m is attached. If you have any suggestion, I'd really appreciate it.
[TP63_1.a3m.zip](https://github.com/patrickbryant1/MoLPC/files/10405686/TP63_1.a3m.zip)

Thank you!
Diogo

**Comment by patrickbryant1** [comment]
Hi, can you also provide the sequences, stoichiometry etc.?

**Comment by diogomaiasilva** [comment]
Here are the params I ran:

Name=TP63
Subsize=2
Sequence=MLYLENNAQTQFSEPQYTNLGLLNSMDQQIQNGSSSTSPYNTDHAQNSVTAPSPYAQPSSTFDALSPSPAIPSNTDYPGPHSFDVSFQQSSTAKSATWTYSTELKKLYCQIAKTCPIQIKVMTPPPQGAVIRAMPVYKKAEHVTEVVKRCPNHELSREFNEGQIAPPSHLIRVEGNSHAQYVEDPITGRQSVLVPYEPPQVGTEFTTVLYNFMCNSSCVGGMNRRPILIIVTLETRDGQVLGRRCFEARICACPGRDRKADEDSIRKQQVSDSTKNGDGTKRPFRQNTHGIQMTSIKKRRSPDDELLYLPVRGRETYEMLLKIKESLELMQYLPQHTIETYRQQQQQQHQHLLQKQTSIQSPSSYGNSSPPLNKMNSMNKLPSVSQLINPQQRNALTPTTIPDGMGANIPMMGTHMPMAGDMNGLSPTQALPPPLSMPSTSHCTPPPPYPTDCSIVSFLARLGCSSCLDYFTTQGLTTIYQIEHYSMDDLASLKIPEQFRHAIWKGILDHRQLHEFSSPSHLLRTPSSASTVSVGSSETRGERVIDAVRFTLRQTISFPPRDEWNDFNFDMDARRNKQQRIKEEGE
STI=4

**Comment by patrickbryant1** [comment]
Hi, this works for me. I don't see the same error.  The result is quite disordered.  I suggest trying to create deeper MSAs and find suitable templates as well as increasing the number of recycles. This is not available in MoLPC currently.
[unrelaxed_model_1.zip](https://github.com/patrickbryant1/MoLPC/files/10413374/unrelaxed_model_1.zip)
