### ISSUE TITLE
Singularity base directory issue in HPC

### ISSUE THREAD

**Issue by diogomaiasilva** [patrickbryant1/MoLPC#11]
I have installed MoLPC in our HPC using the recommended instructions without any apparent errors. However, when I try running the test command "bash pipeline.sh", I get the following error message:

<img width="1070" alt="Screen Shot 2023-01-05 at 1 13 18 PM" src="https://user-images.githubusercontent.com/77847721/210852248-1d42e629-6873-41dd-bdc8-29a9fae7025a.png">

It looks like the base path is not recognized when singularity is executed, and it therefore cannot access scripts that are in the correct folders (I manually checked and there are no path issues).

Has anyone ran into this problem, and, if so, found a solution?

Thank you,
Diogo

**Comment by patrickbryant1** [comment]
Hi, this error is related to your HPC env. You have to make sure that singularity can access the files as you mention. I suggest that you bind the path (https://docs.sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html) you want to ensure that singularity can see. The binding could be: singularity exec --nv --bind data_dir:data_dir $IMG. If this doesn't work you should talk to the maintainers of your HPC env as you probably need to set certain permissions.

**Comment by diogomaiasilva** [comment]
Hi Patrick,

Binding fixed it. Thank you for your help.

Best,
Diogo
