### ISSUE TITLE
TypeError: vmap() missing 1 required keyword-only argument: 'split_rng'

### ISSUE THREAD

**Issue by echoduan** [patrickbryant1/MoLPC#12]
When performing Step2: FOLDING PIPELINE using MoLPC, there is always an error message:
###
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (464) bind mounts
/opt/conda/lib/python3.8/site-packages/absl/flags/_validators.py:233: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  mark_flag_as_required(flag_name, flag_values)
I0109 22:22:38.976617 140038075995968 xla_bridge.py:353] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
I0109 22:22:39.946167 140038075995968 xla_bridge.py:353] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Host CUDA Interpreter
I0109 22:22:39.946772 140038075995968 xla_bridge.py:353] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0109 22:22:39.946953 140038075995968 xla_bridge.py:353] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
I0109 22:22:40.967791 140038075995968 run_alphafold.py:420] Have 1 models: ['model_1']
I0109 22:22:40.968039 140038075995968 run_alphafold.py:436] Using random seed 5221267853343037865 for the data pipeline
I0109 22:22:57.578796 140038075995968 foldonly.py:147] MSA 0 size: 16465 sequences.
I0109 22:22:57.579083 140038075995968 foldonly.py:147] MSA 1 size: 72711 sequences.
I0109 22:22:57.579174 140038075995968 foldonly.py:148] Final (deduplicated) MSA size: 65230 sequences.
I0109 22:22:57.579508 140038075995968 foldonly.py:150] Total number of templates (NB: this can include bad templates and is later filtered to top 4): 0.
I0109 22:22:59.525432 140038075995968 run_alphafold.py:235] Running model model_1
I0109 22:23:42.204971 140038075995968 model.py:131] Running predict with shape(feat) = {'aatype': (4, 663), 'residue_index': (4, 663), 'seq_length': (4,), 'template_aatype': (4, 4, 663), 'template_all_atom_masks': (4, 4, 663, 37), 'template_all_atom_positions': (4, 4, 663, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 663), 'msa_mask': (4, 508, 663), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_pseudo_beta': (4, 4, 663, 3), 'template_pseudo_beta_mask': (4, 4, 663), 'atom14_atom_exists': (4, 663, 14), 'residx_atom14_to_atom37': (4, 663, 14), 'residx_atom37_to_atom14': (4, 663, 37), 'atom37_atom_exists': (4, 663, 37), 'extra_msa': (4, 5120, 663), 'extra_msa_mask': (4, 5120, 663), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 663), 'true_msa': (4, 508, 663), 'extra_has_deletion': (4, 5120, 663), 'extra_deletion_value': (4, 5120, 663), 'msa_feat': (4, 508, 663, 49), 'target_feat': (4, 663, 22)}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/haiku/_src/stateful.py", line 725, in wrapper
    return f(*args, **kwargs)
TypeError: vmap() missing 1 required keyword-only argument: 'split_rng'
........
###
Please tell me how to fix this bug?

**Comment by patrickbryant1** [comment]
Hi,
Are you running MolPC locally? Please provide some more information about your setup. I think this is related to your singularity environment somehow. What version of jax are you getting?

**Comment by echoduan** [comment]
Hi Patrick Bryant,

       Yes, I installed local MoLPC in a GPU server (16G). singularity version=3.9.5, installed by conda since I can't install it following your method on LINUX. JAX version is 0.3.16. 

      I solve the previous bug. But now I have a new bug:

2023-01-09 23:24:51.157717: W external/org_tensorflow/tensorflow/tsl/platform/default/dso_loader.cc:66] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs

       I also want to use your MoLPC.ipynb version. But I have 7 unique sequences. Could you tell me how to modify the default interface?

      
![image](https://user-images.githubusercontent.com/22016970/211589536-a79d6d12-b66f-43b6-a121-b3e5ae994ed3.png)


        When I tested your prepared example, it report a warning message:
![image](https://user-images.githubusercontent.com/22016970/211590152-6583e182-3fbb-4ef4-bf7a-e745c255002d.png)

      Do I need to fix it? how to do it?
       
    Best

**Comment by patrickbryant1** [comment]
Hi, 
For the local installation, it may be that conda is blocking something or that you need to bind your path for singularity to be able to access your files:
singularity exec --nv --bind path/to/data_dir:path/to/data_dir: $SINGIMG python3 ...

For the colab version, you need to set your runtime to GPU. Please read the instructions in the colab notebook again. If you want to add more sequences you have to modify this yourself.
