### ISSUE TITLE
Moving from singularity to apptainer

### ISSUE THREAD

**Issue by SimonKitSangChu** [patrickbryant1/MoLPC#14]
Since singularity is now officially moved to apptainer, would the setup and run script be updated to apptainer? We only have apptainer available on our cluster.

**Comment by patrickbryant1** [comment]
Hi, yes it should be I suppose. Let me look into it. Can you not run singularity images in apptainer?

**Comment by SimonKitSangChu** [comment]
That's good point. I have now changed all `singularity` command to `apptainer`. The next issue I face is a no-such-file-found error. 

For instance, it reports 
```/opt/conda/bin/python3: can't open file '/toolbox/MoLPC/src/preprocess/write_hhblits_fasta.py': [Errno 2] No such file or directory```

while the file exists
```
ls /toolbox/MoLPC/src/preprocess/write_hhblits_fasta.py
/toolbox/MoLPC/src/preprocess/write_hhblits_fasta.py
```

Do you think it is a permission problem? As a users on shared compute, we don't have root access.

**Comment by patrickbryant1** [comment]
I would check these paths. Is your root at "/toolbox" ? I would suspect that this is symlinked somehow. Go to the directory where you installed MoLPC and do "pwd" to check the path. Then provide the output to the scripts. Remember that all paths have to be from root for singularity/apptainer to be able use them.

If this doesn't work - raise an issue with your cluster.

**Comment by SimonKitSangChu** [comment]
Indeed the path is a realpath from root.
```
realpath `pwd`
/toolbox/MoLPC
```

Do you see other potential reasons?

**Comment by patrickbryant1** [comment]
Hi, 
Perhaps you should contact bioinformatics support at your university. 
The command should be only 'pwd' not 'realpath pwd'.
