### ISSUE TITLE
[Colab]GPU RAM Question

### ISSUE THREAD

**Issue by BruceLiuIBP** [patrickbryant1/MoLPC#15]
Hello,
When i try to use MoLPC (Colab version), even using test data, 1A8R, it will have some mistake in the Step2: Folding Pipeine - Predict the subcomponents

"/usr/local/lib/python3.10/dist-packages/haiku/_src/data_structures.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
  PyTreeDef = type(jax.tree_structure(None))
Predicting subcomponent 1A8R_1-1-1"

and the colab will restart due to GPU RAM overload, here is the app.log
![image](https://github.com/patrickbryant1/MoLPC/assets/106569881/75ef49e7-3f14-474a-8e06-80fb02296035)

My Running condition: 
I use free version of colab , it give me T4 GPU, 15 G RAM, runing the test case 1A8R, subsize 3 , st1 10 (3 can not work as well)

How can I solve the problem?

Thank you very much.

**Comment by patrickbryant1** [comment]
Hi, these are not errors - only warnings. If you are OOM you can try to reduce the sequence lengths. The test case should work according to other users. I can't see that your process terminated in your log?
