### ISSUE TITLE
ERROR: Failed building wheel for numpy

### ISSUE THREAD

**Issue by osnatherzberg** [patrickbryant1/MoLPC#16]
Hello Patrick,
I have just started using the MolPC and the Install dependencies failed with the message that it failed building wheel for numpy.

error: subprocess-exited-with-error
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for numpy (pyproject.toml) ... error
  ERROR: Failed building wheel for numpy
Failed to build numpy

 Can you help? In case you need it, below is the entire window:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Requirement already satisfied: jax[cuda]==0.3.22 in /usr/local/lib/python3.10/dist-packages (0.3.22)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from jax[cuda]==0.3.22) (1.4.0)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from jax[cuda]==0.3.22) (1.22.4)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.10/dist-packages (from jax[cuda]==0.3.22) (3.3.0)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.10/dist-packages (from jax[cuda]==0.3.22) (1.10.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from jax[cuda]==0.3.22) (4.5.0)
Requirement already satisfied: etils[epath] in /usr/local/lib/python3.10/dist-packages (from jax[cuda]==0.3.22) (1.2.0)
Requirement already satisfied: jaxlib==0.3.22+cuda11.cudnn82 in /usr/local/lib/python3.10/dist-packages (from jax[cuda]==0.3.22) (0.3.22+cuda11.cudnn82)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.10/dist-packages (from etils[epath]->jax[cuda]==0.3.22) (5.12.0)
Requirement already satisfied: zipp in /usr/local/lib/python3.10/dist-packages (from etils[epath]->jax[cuda]==0.3.22) (3.15.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: biopython==1.79 in /usr/local/lib/python3.10/dist-packages (1.79)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from biopython==1.79) (1.22.4)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: dm-haiku==0.0.7 in /usr/local/lib/python3.10/dist-packages (0.0.7)
Requirement already satisfied: absl-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from dm-haiku==0.0.7) (1.4.0)
Requirement already satisfied: jmp>=0.0.2 in /usr/local/lib/python3.10/dist-packages (from dm-haiku==0.0.7) (0.0.4)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.10/dist-packages (from dm-haiku==0.0.7) (1.22.4)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.10/dist-packages (from dm-haiku==0.0.7) (0.8.10)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: ml-collections==0.1.0 in /usr/local/lib/python3.10/dist-packages (0.1.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from ml-collections==0.1.0) (1.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from ml-collections==0.1.0) (6.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from ml-collections==0.1.0) (1.16.0)
Requirement already satisfied: contextlib2 in /usr/local/lib/python3.10/dist-packages (from ml-collections==0.1.0) (0.6.0.post1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: chex==0.0.7 in /usr/local/lib/python3.10/dist-packages (0.0.7)
Requirement already satisfied: absl-py>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chex==0.0.7) (1.4.0)
Requirement already satisfied: dm-tree>=0.1.5 in /usr/local/lib/python3.10/dist-packages (from chex==0.0.7) (0.1.6)
Requirement already satisfied: jax>=0.1.55 in /usr/local/lib/python3.10/dist-packages (from chex==0.0.7) (0.3.22)
Requirement already satisfied: jaxlib>=0.1.37 in /usr/local/lib/python3.10/dist-packages (from chex==0.0.7) (0.3.22+cuda11.cudnn82)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.10/dist-packages (from chex==0.0.7) (1.22.4)
Requirement already satisfied: toolz>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chex==0.0.7) (0.12.0)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.10/dist-packages (from jax>=0.1.55->chex==0.0.7) (3.3.0)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.10/dist-packages (from jax>=0.1.55->chex==0.0.7) (1.10.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from jax>=0.1.55->chex==0.0.7) (4.5.0)
Requirement already satisfied: etils[epath] in /usr/local/lib/python3.10/dist-packages (from jax>=0.1.55->chex==0.0.7) (1.2.0)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.10/dist-packages (from etils[epath]->jax>=0.1.55->chex==0.0.7) (5.12.0)
Requirement already satisfied: zipp in /usr/local/lib/python3.10/dist-packages (from etils[epath]->jax>=0.1.55->chex==0.0.7) (3.15.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: dm-tree==0.1.6 in /usr/local/lib/python3.10/dist-packages (0.1.6)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: immutabledict==2.0.0 in /usr/local/lib/python3.10/dist-packages (2.0.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting numpy==1.19.5
  Using cached numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: numpy
  error: subprocess-exited-with-error
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for numpy (pyproject.toml) ... error
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas==1.3.4 in /usr/local/lib/python3.10/dist-packages (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.4) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.4) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.4) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7.3->pandas==1.3.4) (1.16.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement scipy==1.7.0 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1, 1.11.0rc1, 1.11.0rc2)
ERROR: No matching distribution found for scipy==1.7.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu==2.5.0 (from versions: 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2)
ERROR: No matching distribution found for tensorflow-cpu==2.5.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: py3Dmol in /usr/local/lib/python3.10/dist-packages (2.0.3)

**Comment by patrickbryant1** [comment]
Hi, I am not sure what causes this error. Perhaps this is related to some remission issue for writing new packages to your user?

**Comment by osnatherzberg** [comment]
Hello Patrick,

I asked my colleague, Professor Brian Pierce, to run the colab on his computer and he got the same error massage. This is what he wrote:

I just tried the Colab again now, and after it prompted me about google drive access (and I accepted), it installed most packages but still seemed to error out with the numpy installation. So the problem does not seem to be the google drive access as Patrick mentioned, as far as I can tell.

Regards,
Osnat
—————————
Osnat Herzberg, PhD
Professor
Institute for Bioscience and Biotechnology Research
University of Maryland
9600 Gudelsky Drive
Rockville, MD 20850
USA
Tel 240-314-6245 
Fax 240-314-6255 
E-mail ***@***.***

**Comment by patrickbryant1** [comment]
Hi,

I understand what you are referring to now. I thought this was an issue with local installation, but is in fact related to the Colab. It seems that Google has updated python to 3.8 (and changed some other things as well). We will look into migrating the code to 3.8 or see if we can resolve this somehow else. In the meantime, local installation may be easier.

Best,

Patrick

**Comment by patrickbryant1** [comment]
Hi, 
I tried to run the Colab notebook and have no issues installing the packages. Can you please try it again?

Best,

Patrick

**Comment by osnatherzberg** [comment]
Hi Patrick,

I run your test example (1A8R_1) and it gave the same error messages. However, the job completed successfully. In contrast, when I tried my own sequence and an .a3m file (smMreb3_1) the job failed at the MSA pipeline with a file not found massage:

Creating all interactions of size 3 ...
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-27-092e0164392d> <https://a1nsd5mgb4q-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230725-060148-RC00_550839261#> in <cell line: 21>()
     19 ***@***.*** Write the Paired and Block Diagonalized MSAs to predict sub-components
     20 from preprocess import preprocess_colab
---> 21 preprocess_colab.create_folder_structure(MSADIR, ID, OUTDIR, USEQS, INTERACTIONS, CHAINS, GET_ALL, SUBSIZE)

2 frames
/content/MoLPC/src/preprocess/preprocess_colab.py <https://a1nsd5mgb4q-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230725-060148-RC00_550839261#> in read_a3m(infile, max_gap_fraction)
     29     seqlen = 0
     30     lc = 0
---> 31     with open(infile, 'r') as file:
     32         for line in file:
     33             line = line.rstrip()

FileNotFoundError: [Errno 2] No such file or directory: '/content/MoLPC/data/test/smMreb3_1_1.a3m’

After first uploading the MSA file to /content, I uploaded the smMreb3_1.a3m file to /content/MolPC/data/test. Then I tried to change all the names including in the ID and MSA1 to smMreb3_1_1.a3m. It still did not work. 

Attached is my .a3m file. I tried to generate a 6-mer but since the program failed before reading the a3m file, presumably this is not important.
Any insight?

Regards,
Osnat

------------------
Osnat Herzberg, PhD
Professor
Institute for Bioscience and Biotechnology Research
University of Maryland
9600 Gudelsky Drive
Rockville, MD 20850
USA
Tel 240-314-6245 
Fax 240-314-6255 
E-mail ***@***.*** ***@***.***>

**Comment by patrickbryant1** [comment]
Hi,
Great to see that the test example is working for you as well. I don't think it is an error you are receiving when installing the packages in colab, rather an intermediate incompatibility warning that is fixed later.

I think the issue is that your naming is incorrect. 
Note that you have to follow the naming convention:
"Make sure to name your MSAs according to the convention ID_1, ..., ID_N (both here and for the uploaded files)"

Try setting the ID = smMreb3 (no suffix)
and naming MSA 1 "smMreb3_1" and upload the file "smMreb3_1.a3m"

Note that computer programs require exact information and if you upload/name files other than you specify in the input these will not be found as you can read from the error message:
"FileNotFoundError: [Errno 2] No such file or directory: '/content/MoLPC/data/test/smMreb3_1_1.a3m’"

We have tried to make the running of MoLPC as easy as possible, but I am sure you understand that the code itself is actually quite complicated and we can't handle all possible cases of different naming schemes.

Hope this helps and please get back to us if you have any further issues.

Best,

Patrick

**Comment by osnatherzberg** [comment]
Hi Patrick,

Thank you for your advice. This time it worked. I previously made a mistake with the ID record, adding a _1 to it. Unfortunately, when I was preparing my next run, I inadvertently cleared the AF/params file (/content/gdrive/MyDrive/AF/params/params_model_1.npz’) and related files. the job failed with the message: 
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/AF/params/params_model_1.npz'

Indeed, the params directory is empty (except for the License, which I did not delete). How do I get it back?

Also, are you using the latest AlphaFold multimer version that allows for >1400 amino acids? Could you link that version to MolPC? It would be most useful for me as I have a protein  with >500 aa.

Regards
------------------
Osnat Herzberg, PhD
Professor
Institute for Bioscience and Biotechnology Research
University of Maryland
9600 Gudelsky Drive
Rockville, MD 20850
USA
Tel 240-314-6245 
Fax 240-314-6255 
E-mail ***@***.***
