### ISSUE TITLE
non-deterministic output confirmation and recommendations

### ISSUE THREAD

**Issue by chris-desjardins** [patrickbryant1/MoLPC#17]
Hi, excited to use MoLPC to assembly symmetrical protein structures. I've been try to replicate your paper results with 1DPS. I had issues with Singularity install on Google Cloud Platform. So I did a local install of hhsuite on a VM, and generated an MSA using the command from this repo. Next, I opened the colab notebook in Google's Vertex AI workbench and ran it from there, using the 1DPS monomer sequence from PDB, 12 chains, and the resulting MSA.

I've run the notebook four times and have gotten premature termination of the run each time (due to overlap, I assume). The assemblies I've gotten so far are:

```
| Run # | Chains | mpDOCKQ |
| ----- | ------ | ------- |
| 1     | 5      | 0.68    |
| 2     | 8      | 0.73    |
| 3     | 11     | 0.94    |
| 4     | 5      | 0.72    |
```

I'm wondering if this is intended behaviour, and if so, if you have a recommended number of times to run a structure before choosing an optimal one. Thank you.

**Comment by patrickbryant1** [comment]
Hi, the output will depend on the msa samples. If you get a high score I would take that structure. I have not observed this large variation, but we have not really looked into this.

**Comment by patrickbryant1** [comment]
If you run a varying amount of chains, the mpDockQ should likely vary. When you run 5 chains, the score seems stable (0.7)
