### ISSUE TITLE
ValueError during subcomponent prediction

### ISSUE THREAD

**Issue by EEvangelisti** [patrickbryant1/MoLPC#19]
Hello,

Thank you for developing a MoLPC Colab, this is a great tool!

I am trying to use it for a PIEZO-type receptor that works as homotrimer. The monomer is very large (~2800 aa). I was able to run the Colab until subcomponent prediction. I then got the following error:

```
/usr/local/lib/python3.10/dist-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Predicting subcomponent PIEZO_1-1-1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-6-39acb0e34368>](https://localhost:8080/#) in <cell line: 14>()
     30   BLOCKEDMSA=OUTDIR+sub_id+'_blocked.a3m'
     31   MSAS=[PAIREDMSA,BLOCKEDMSA] #Comma separated list of msa paths
---> 32   run_alphafold_colab.main([MODEL_NAME], 1, MAX_RECYCLES, STRUCTURE_DIR, FASTAFILE, sub_id, MSAS, CB, OUTDIR)

7 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py](https://localhost:8080/#) in _create_c_op(graph, node_def, inputs, control_inputs, op_def, extract_traceback)
   1965   except errors.InvalidArgumentError as e:
   1966     # Convert to ValueError for backwards compatibility.
-> 1967     raise ValueError(e.message)
   1968 
   1969   # Record the current Python stack trace as the creating stacktrace of this

ValueError: Cannot reshape a tensor with 60 elements to shape [4,8526,1] (34104 elements) for '{{node reshape_msa}} = Reshape[T=DT_INT32, Tshape=DT_INT32](Const_6, reshape_msa/shape)' with input shapes: [4,15], [3] and with input tensors computed as partial shapes: input[1] = [4,8526,1].
```
In the cell above, I have ID = PIEZO, SUBSIZE = 3, USEQ1 = the 2800 aa sequence, ST1 = 3, MSA1 = PIEZO_1.a3m 
The check box is unticked, and the PIEZO_1.a3m file has been uploaded.

I have attached the files with the sequence (PIEZO.fas) and the alignment (PIEZO.a3m):
[PIEZO.zip](https://github.com/patrickbryant1/MoLPC/files/14623641/PIEZO.zip)

I must be doing something wrong but I cannot figure it out.

Could you please help? Thank you very much!

Edouard

**Comment by patrickbryant1** [comment]
Hi,

I think the problem seems to be related to the MSA. Something seems to be off in there causing shape mismatches. Please check the sequence and msa again.

Best,

Patrick

**Comment by EEvangelisti** [comment]
Thank you for your fast reply. I re-generated the MSA file, but that did not help. I have checked the files generated by the script. Here is PIEZO_1-1-1_blocked.a3m:

```
>0
-A-M-----------
>1
------A-M------
>2
-----------A-M-
```

And then file PIEZO_1-1-1_paired.a3m:
```
>0
-A-M--A-M--A-M-
```

There is also a file called PIEZO_1-1-1.fasta, which contains a concatenation of the three monomers (header is `>PIEZO_1-1-1|2842-2842-2842`).

I don't know what is wrong there, as the error is still the same.

Best regards,
Edouard

**Comment by patrickbryant1** [comment]
It seems like you have run very short sequences and the MSAs contain no information. Please make sure you are inputting the sequences correctly.

**Comment by EEvangelisti** [comment]
Thanks. I double-checked my files and eventually figured out that the name of my sequence of interest in the a3m file should have been PIEZO_1 instead of PIEZO. I was able to move forward with the Colab script. Unfortunately, my input is too large and results in memory exhaustion. Still, I will use it with other candidates. Thank you again for your help in troubleshooting this. Regards
