### ISSUE TITLE
module 'jax' has no attribute 'tree_multimap' 

### ISSUE THREAD

**Issue by pillepalle123** [patrickbryant1/MoLPC#2]
With the test set on Colab I am running into:

module 'jax' has no attribute 'tree_multimap' 

according to  [stackoverflow](https://stackoverflow.com/questions/73693738/module-jax-has-no-attribute-tree-multimap-in-alphafold2-colab) this do to jax.tree_multimap is being replaced by jax.tree_map. alternatively 

`!pip install "jax<=0.3.16" "jaxlib<=0.3.16"`

could be used.

thx

**Comment by pillepalle123** [comment]
I replaced 

!pip install JAX
with
!pip install "jax<=0.3.16" "jaxlib<=0.3.16"

but still got:

`/content/my-bucket/haiku/_src/data_structures.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
  PyTreeDef = type(jax.tree_structure(None))

Predicting subcomponent 1A8R_1-1-1

/content/my-bucket/haiku/_src/data_structures.py:195: FutureWarning: jax.tree_flatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_flatten instead.
  leaves, structure = jax.tree_flatten(mapping)
/content/my-bucket/haiku/_src/data_structures.py:203: FutureWarning: jax.tree_unflatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_unflatten instead.
  self._mapping = jax.tree_unflatten(self._structure, self._leaves)
/content/MoLPC/src/AF2/alphafold/model/mapping.py:49: FutureWarning: jax.tree_flatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_flatten instead.
  values_tree_def = jax.tree_flatten(values)[1]
/content/MoLPC/src/AF2/alphafold/model/mapping.py:53: FutureWarning: jax.tree_unflatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_unflatten instead.
  return jax.tree_unflatten(values_tree_def, flat_axes)

---------------------------------------------------------------------------

UnfilteredStackTrace                      Traceback (most recent call last)

[<ipython-input-7-65e446b9a7f9>](https://localhost:8080/#) in <module>
     28   MSAS=[PAIREDMSA,BLOCKEDMSA] #Comma separated list of msa paths
---> 29   run_alphafold_colab.main([MODEL_NAME], 1, MAX_RECYCLES, STRUCTURE_DIR, FASTAFILE, sub_id, MSAS, CB, OUTDIR)

71 frames

UnfilteredStackTrace: AttributeError: module 'jax' has no attribute 'tree_multimap'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------


The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)

[/content/MoLPC/src/AF2/alphafold/model/mapping.py](https://localhost:8080/#) in mapped_fn(*args)
    121     in_axes_ = _expand_axes(in_axes, args)
    122 
--> 123     in_sizes = jax.tree_multimap(_maybe_get_size, args, in_axes_)
    124     flat_sizes = jax.tree_flatten(in_sizes)[0]
    125     in_size = max(flat_sizes)

AttributeError: module 'jax' has no attribute 'tree_multimap'`

**Comment by mau-reen** [comment]
Hello,

I found that

!pip install "jax<=0.3.15"
!pip install -U jaxlib==0.3.15+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

and it seems to work

**Comment by patrickbryant1** [comment]
Hi,
This issue is due to Google changing things in their Colab. We have fixed this now by updating some of the code.
