### ISSUE TITLE
About the data redundancy removal

### ISSUE THREAD

**Issue by zqgao22** [patrickbryant1/MoLPC#20]
Hi the MoLPC team,

What a nice work. 

May I ask how to find the codes to perform the step in the green box in Fig. 6. That is: the step 1027-->265 complexes.

Best.

**Comment by patrickbryant1** [comment]
Hi,

This is done with join commands on the pdb ids and clusters within them. This you have to implement yourself given the instructions. Is there something specific you are looking for?

Best,

Patrick
