### ISSUE TITLE
MoLPC colab error

### ISSUE THREAD

**Issue by a-bio90** [patrickbryant1/MoLPC#3]
By attempting to run the Colab version of MoLPC I got stuck at the MSA pipeline cell:
https://colab.research.google.com/github/patrickbryant1/MoLPC/blob/master/MoLPC.ipynb?authuser=1#scrollTo=gdefazeqnSrp&line=21&uniqifier=1

It reports the following error:
```
FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-9-c615f0ba5e54>](https://localhost:8080/#) in <module>
     19 #@markdown Write the Paired and Block Diagonalized MSAs to predict sub-components
     20 from preprocess import preprocess_colab
---> 21 preprocess_colab.create_folder_structure(MSADIR, ID, OUTDIR, USEQS, INTERACTIONS, CHAINS, GET_ALL, SUBSIZE)
```

By running the test case the pipeline works just fine. I also installed the dependencies by following the instructions.

Thanks in advance

**Comment by patrickbryant1** [comment]
Hi,
It looks like you need to clone the git into the runtime again. Please try this and get back if it still doesn't work.

**Comment by a-bio90** [comment]
Thanks for the answer.
I tried to re-run the clone git window again but same result. If I use just 1 protein sequence as input (with a corresponding MSA file) the MSA cell works just fine. But when I try to put more than one protein sequence it gives the same error back. Am I missing something?

**Comment by patrickbryant1** [comment]
I think this must be related to how you name the files. Could you provide some more information - perhaps a screen shot?

**Comment by a-bio90** [comment]
Yes, here are two screenshots of the error and input setup. Thanks

![Screenshot 2022-10-18 at 19 36 44](https://user-images.githubusercontent.com/91066733/196504302-c09bb94a-1321-44c7-a3c4-80f7b668a6d4.png)
![Screenshot 2022-10-18 at 19 37 02](https://user-images.githubusercontent.com/91066733/196504311-bb1cfc79-c8dd-4275-b81c-7548a2cf91fc.png)
