### ISSUE TITLE
Singularity / cuSolver internal error

### ISSUE THREAD

**Issue by rhysDevans97** [patrickbryant1/MoLPC#5]
Hello,

I appear to be getting the following error when running the folding prediction (singularity exec $SINGIMG run_alphafold.py ...) from pipeline.sh on my local HPC cluster (nvidia quadro RTX 6000) using the test case, 1A8R (run using sbatch). This cluster already had singularity installed so I have not run the install_singularity_ubuntu.sh script as I do not have permissions to run the sudo commands; unsure if this is relevant though; it is version 3.8.5-2.e18. I have run the setup script, however, so the singularity container is installed and has worked fine in the Step 1 of the script.

From reading online about "cuSolver internal error", I thought it may be due to the GPU usage, so have also tried adding the following to the top of the run_alphafold.py script; though it does not seem to have affected the error:
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"

Here is the slurm output.

1A8R_1-1-1
/opt/conda/lib/python3.8/site-packages/haiku/_src/data_structures.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
  PyTreeDef = type(jax.tree_structure(None))
/opt/conda/lib/python3.8/site-packages/absl/flags/_validators.py:233: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  mark_flag_as_required(flag_name, flag_values)
I1019 11:13:34.158577 22964222310208 xla_bridge.py:350] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I1019 11:13:34.462544 22964222310208 xla_bridge.py:350] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Host CUDA Interpreter
I1019 11:13:34.464354 22964222310208 xla_bridge.py:350] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I1019 11:13:35.027019 22964222310208 run_alphafold.py:420] Have 1 models: ['model_1']
I1019 11:13:35.027183 22964222310208 run_alphafold.py:436] Using random seed 2249254576644360651 for the data pipeline
I1019 11:13:46.612542 22964222310208 foldonly.py:147] MSA 0 size: 16465 sequences.
I1019 11:13:46.614010 22964222310208 foldonly.py:147] MSA 1 size: 72711 sequences.
I1019 11:13:46.614062 22964222310208 foldonly.py:148] Final (deduplicated) MSA size: 65230 sequences.
I1019 11:13:46.614251 22964222310208 foldonly.py:150] Total number of templates (NB: this can include bad templates and is later filtered to top 4): 0.
I1019 11:13:46.931220 22964222310208 run_alphafold.py:235] Running model model_1
I1019 11:15:21.782771 22964222310208 model.py:131] Running predict with shape(feat) = {'aatype': (11, 663), 'residue_index': (11, 663), 'seq_length': (11,), 'template_aatype': (11, 4, 663), 'template_all_atom_masks': (11, 4, 663, 37), 'template_all_atom_positions': (11, 4, 663, 37, 3), 'template_sum_probs': (11, 4, 1), 'is_distillation': (11,), 'seq_mask': (11, 663), 'msa_mask': (11, 508, 663), 'msa_row_mask': (11, 508), 'random_crop_to_size_seed': (11, 2), 'template_mask': (11, 4), 'template_pseudo_beta': (11, 4, 663, 3), 'template_pseudo_beta_mask': (11, 4, 663), 'atom14_atom_exists': (11, 663, 14), 'residx_atom14_to_atom37': (11, 663, 14), 'residx_atom37_to_atom14': (11, 663, 37), 'atom37_atom_exists': (11, 663, 37), 'extra_msa': (11, 5120, 663), 'extra_msa_mask': (11, 5120, 663), 'extra_msa_row_mask': (11, 5120), 'bert_mask': (11, 508, 663), 'true_msa': (11, 508, 663), 'extra_has_deletion': (11, 5120, 663), 'extra_deletion_value': (11, 5120, 663), 'msa_feat': (11, 508, 663, 49), 'target_feat': (11, 663, 22)}
**2022-10-19 11:15:56.384415: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs**
/opt/conda/lib/python3.8/site-packages/haiku/_src/data_structures.py:144: FutureWarning: jax.tree_flatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_flatten instead.
  leaves, treedef = jax.tree_flatten(tree)
/opt/conda/lib/python3.8/site-packages/haiku/_src/data_structures.py:145: FutureWarning: jax.tree_unflatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_unflatten instead.
  return jax.tree_unflatten(treedef, leaves)
/opt/conda/lib/python3.8/site-packages/haiku/_src/stateful.py:771: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  if not jax.tree_leaves(in_axes):
/home/MoLPC/src/AF2/alphafold/model/mapping.py:49: FutureWarning: jax.tree_flatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_flatten instead.
  values_tree_def = jax.tree_flatten(values)[1]
/home/MoLPC/src/AF2/alphafold/model/mapping.py:53: FutureWarning: jax.tree_unflatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_unflatten instead.
  return jax.tree_unflatten(values_tree_def, flat_axes)
/home/MoLPC/src/AF2/alphafold/model/mapping.py:124: FutureWarning: jax.tree_flatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_flatten instead.
  flat_sizes = jax.tree_flatten(in_sizes)[0]
/opt/conda/lib/python3.8/site-packages/haiku/_src/stateful.py:575: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  length = jax.tree_leaves(xs)[0].shape[0]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/jax/interpreters/mlir.py", line 1122, in _lower_jaxpr_to_fun_cached
    func_op = ctx.cached_call_jaxpr_lowerings[key]
**KeyError: ('eigh', { lambda ; a:f32[1,663,4,4]. let
    b:f32[1,663,4,4] = transpose[permutation=(0, 1, 3, 2)] a
    c:f32[1,663,4,4] = add a b
    d:f32[1,663,4,4] = div c 2.0
    e:f32[1,663,4,4] f:f32[1,663,4] = eigh[lower=True sort_eigenvalues=True] d
  in (f, e) }, ())**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/MoLPC/src/AF2/run_alphafold.py", line 460, in <module>
    app.run(main)
...
...
**jax._src.source_info_util.JaxStackTraceBeforeTransformation: RuntimeError: jaxlib/cuda/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error**

**Comment by patrickbryant1** [comment]
Hi,
This appears to be a problem with the cuda on your cluster and not with MolPC. I suggest contacting the support at your cluster. It may be that the cuda version in singularity doesn't match the one on your cluster.

**Comment by metteroes** [comment]
Hi, excited to use your software.
However, I'm having the exact same problem. My hpc support person tells me that cuda is already in the MoLPC alphafold container, and I therefore don't use the cuda on the cluster, and to open a github issue about it. What now? :)

**Comment by metteroes** [comment]
I am using a nvidia a100 GPU, so the same as in the paper.

**Comment by metteroes** [comment]
@rhysDevans97 did you find a solution?

**Comment by rhysDevans97** [comment]
> @rhysDevans97 did you find a solution?

I’m afraid not. In the end I gave up and paid for one month of Colab Pro and used the Notebook version instead which worked without issue. Sorry I couldn’t be of more help!

**Comment by patrickbryant1** [comment]
Hi,There may be many reasons this failed on your cluster. The most likely is incompatible versions of the cuda inside your singularity image and at the cluster. Another problem may be that singularity doesn't have access to what it needs at your cluster.I don't think this is a code issue. Please ask your support.Best,Patrick On Nov 16, 2022 17:00, metteroes ***@***.***> wrote:
Hi, excited to use your software.
However, I'm having the exact same problem. My hpc support person tells me that cuda is already in the MoLPC alphafold container, and I therefore don't use the cuda on the cluster, and to open a github issue about it. What now? :)
