### ISSUE TITLE
MoLPC colab error

### ISSUE THREAD

**Issue by debadutta-patra** [patrickbryant1/MoLPC#7]
Hi,

When I am trying to run MoLPC for my proteins, I am getting  The following ValueError. 

Please help
![Screenshot 2022-10-21 155621](https://user-images.githubusercontent.com/38185922/197174856-2fccdac2-f2b1-4b9f-990b-6843ac747596.png)

**Comment by patrickbryant1** [comment]
Hi,
I think this may be related to how you generated the a3m file. Is it possible that the header is generated from some kind of custom options?

**Comment by debadutta-patra** [comment]
I tried running the test data, but surprisingly I got the exact same error message. 
I also looked through my a3m file and I can't find the mentioned entry in my file, so I believe it's not coming from my alignment file.

**Comment by patrickbryant1** [comment]
Ok, I am not sure why this is. The test data should work. Could you go over the naming of your example again and compare it with the test?

**Comment by debadutta-patra** [comment]
Hey,
Thanks for replying. As it turned out, the colab notebook was reading some other unrelated file in my Google Drive which it was unable to parse. I deleted all fasta and a3m files from my account and now the code is running fine.
