### ISSUE TITLE
About msa error

### ISSUE THREAD

**Issue by AhmetGG** [patrickbryant1/MoLPC#9]
Hi,

When I try to use MoLPC, it gives the error that MSA 0 must be at least one sequence. However, in that case, I used the test case, and I got the same error. How can I solve this problem?

**Comment by patrickbryant1** [comment]
Hi, please try and reset the notebook. There is definitely information in the MSA of the test case. This has been verified by many users. If this still doesn't work, please provide more details of exactly what you are doing.

**Comment by AhmetGG** [comment]
Hi,Thank you for your helping. When I tried it again , I got the same error message in the test case.But I am not sure where I make a mistake. I only run google colab with GPU and there was no any parameter I changed. Maybe my colab can be problematic if you are still running it without mistakes.

**Comment by patrickbryant1** [comment]
Hi, please check the MSA again and compare with the test case: https://github.com/patrickbryant1/MoLPC/blob/master/data/test/1A8R_1.a3m

Can you perhaps show the first rows here?

**Comment by AhmetGG** [comment]
Hi, at this time, I managed to run it without an error. Many thanks for your help.
